Controllers/LoginController.cs
using DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaDeCondominios.Models;
using static DataModels.PviProyectoFinalDBStoredProcedures;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Menu;

namespace SistemaDeCondominios.Controllers
{
    public class LoginController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Autenticacion(PersonaModel model)
        {
            try
            {
                using (var db = new PviProyectoFinalDB("MyDatabase"))
                {
                    var persona = db.SpAutenticarUsuario(model.Email, model.Clave).FirstOrDefault();
                    if (persona != null)
                    {
                        Session["idPersona"] = persona.Id_persona;
                        Session["NombreCompleto"] = $"{persona.Nombre}{persona.Apellido}";
                        Session["Email"] = persona.Email;
                        Session["EsEmpleado"] = persona.Tipo_persona;
                        return RedirectToAction("Index","Cobros");
                    }
                    else
                    {
                        ViewBag.Mensaje = "Usuario o Contraseña incorrectos.";
                    }

                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Algo ha salido mal:" + ex;
            }
            return View(model);
        }
        public ActionResult LogOut()
        {
            Session.Remove("idPersona");
            Session.Remove("NombreCompleto");
            Session.Remove("Email");
            Session.Remove("EsEmpleado");
            Session.Clear();
            Session.Abandon();
            
            return RedirectToAction("Index", "Home");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ADMICONDO</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://code.jquery.com/ui/1.14.0/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <a href="@Url.Action("Index", "Home", new { area = "" })" class="navbar-brand">
                <img src="~/Images/LogoNavBar.png" alt="AdmiCondo" style="height: 40px;" />
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Session["idPersona"] != null) // Verifica si hay una sesión activa
                    {
                        if (Session["EsEmpleado"]?.ToString() == "Empleado")//Importante para mostrar diferentes vistas dependiendo de si es empleado o no
                        {
                            <li>@Html.ActionLink("Gestionar Cobros", "Index", "Cobros", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Gestionar Casas", "Index", "Casas", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Gestionar Servicios", "Index", "Servicios", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Mis Cobros", "Index", "Cobros", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (Session["idPersona"] != null) // Verifica si hay una sesión activa
                    {
                        <li class="nav-item">
                            <span class="nav-link"> @Session["NombreCompleto"]</span> <!-- Muestra el nombre completo -->
                        </li>
                        <li><a href="#" class="nav-link" onclick="confirmarCerrarSesion(event, '@Url.Action("LogOut", "Login")')">Cerrar Sesión</a></li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Iniciar Sesión", "Index", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ADMICONDO</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script>
    function confirmarCerrarSesion(event, logoutUrl) {
        event.preventDefault(); // Evita que el enlace se siga automáticamente
        if (confirm("¿Está seguro de que desea cerrar sesión?")) {
            window.location.href = logoutUrl; // Redirige al cerrar sesión si confirma
        }
    }
</script>